resolver: lts-3.14

packages:
- '.'

extra-deps:
- applicative-numbers-0.1.3
- music-dynamics-literal-1.9.0
- music-pitch-literal-1.9.0
- musicxml2-1.9.0
- reverse-apply-2.0.1
- threepenny-gui-0.6.0.4
- ty-0.1.6
- type-unary-0.2.21
- websockets-snap-0.9.2.0
